### ISSUE TITLE
No SettingsTab visible

### ISSUE THREAD

**Issue by Taankly** [Gurkengewuerz/nodebb-plugin-teamspeak-verify#1]
Hey,

i installed the plugin but there is no settings tab visible in the backend. 
On the profile Page there is the Tab "Teamspeak ID" visible and it works...

Also i don't get any errors in the log files.

Used Nodebb version: v1.7.5

Any ideas?

Best regards
Taankly

**Comment by Gurkengewuerz** [comment]
Hey @Taankly ,
No error log? Strange...
On my production system i use NodeBB v1.6.1.

Do you have the steps to reproduce?

**Comment by Taankly** [comment]
Its pretty much a fresh installation of nodebb.

I installed the plugin with "npm install nodebb-plugin-teamspeak-verify".
Restarted nodebb.

Here picture of the installed and activated plugins
<img width="788" alt="screen shot 2018-02-16 at 20 54 31" src="https://user-images.githubusercontent.com/10605140/36326539-b7b0bb60-135b-11e8-9bc0-148a2fc773aa.png">

I can't give you more Informations.... because of no error log etc.. 

What do you need to help?

**Comment by Taankly** [comment]
I found a work around. Because of i can't get to the config Tab just simply type in the search form in the Backend "teamspeak" and you will get to the site where you can set your teamspeak server ip, query login etc. 

After filling in the informations and reloading it works fine!

**Comment by Gurkengewuerz** [comment]
Alright thanks for the info! I try to fix this issue in the new version.

**Comment by Gurkengewuerz** [comment]
Fixed after months. See https://github.com/Gurkengewuerz/nodebb-plugin-teamspeak-verify/issues/2
